version: '3'
services:
  report-app:
    image: hubidu27/report-app:latest
    ports:
      - 8000:4000
    links:
      - report-service
    volumes:
      - /data/e2e-reports:/opt/app/reports

  report-importer:
    image: hubidu27/report-importer:latest
    links:
      - mongodb
    volumes:
      - /data/e2e-reports:/go/src/app/reports
      
  report-service:
    image: hubidu27/report-service:latest
    ports:
      - 8001:8001
    links:
      - mongodb
      
  mongodb:
    image: mongo:3.0
    command: mongod --smallfiles --quiet --logpath=/dev/null
    volumes:
      - /data/db:/data/db
      - /data/configdb:/data/configdb
