version: '3'
services:
  report-importer:
    build: hubidu27/report-importer
    links:
      - mongodb
    volumes:
      - /data/e2e-reports:/go/src/app/reports
      
  report-service:
    build: hubidu27/report-service
    ports:
      - 8000:8000
    links:
      - mongodb
      
  mongodb:
    image: mongo:3.0
    command: mongod --smallfiles --quiet --logpath=/dev/null
    volumes:
      - /data/db:/data/db
      - /data/configdb:/data/configdb
