version: '3'
services:
  report-app:
    restart: always
    image: hubidu27/report-app:latest
    ports:
      - 4000:4000
    links:
      - report-service
    volumes:
      - /data/e2e-reports:/opt/app/reports
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  report-importer:
    restart: always
    image: hubidu27/report-importer:latest
    links:
      - mongodb
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/e2e-reports:/go/src/app/reports
      
  report-service:
    restart: always
    image: hubidu27/report-service:latest
    ports:
      - 8001:8000
    links:
      - mongodb
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/e2e-reports:/go/src/app/reports

  deployment-service:
    restart: always
    image: hubidu27/deployment-service:latest
    ports:
      - 8002:8000
    links:
      - mongodb
    environment:
      - BAMBOO_HOST=${BAMBOO_HOST}
      - BAMBOO_USER=${BAMBOO_USER}
      - BAMBOO_PASSWORD=${BAMBOO_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  # alert-service:
  #   restart: always
  #   image: hubidu27/alert-service:latest
  #   links:
  #     - report-service
  #   environment:
  #     - SMTP_HOST=${SMTP_HOST}
  #     - SMTP_PORT=25
  #     - ALERT_FROM=${ALERT_FROM}
  #     - ALERT_RECIPIENTS=${ALERT_RECIPIENTS}
  #   volumes:
  #     - /etc/timezone:/etc/timezone
  #     - /etc/localtime:/etc/localtime

  # selenium-chrome:
  #   privileged: true
  #   # image: elgalu/selenium:3.7.1-p7
  #   image: elgalu/selenium:3.7.1-p7
  #   environment:
  #     - JAVA_OPTS=-Xmx1248m
  #     # - MAX_INSTANCES=2
  #     # - MAX_SESSIONS=2
  #     # - CHROME=true
  #     # - FIREFOX=false
  #     # - VIDEO=false
  #     - NODE_MAX_INSTANCE=5
  #     - NODE_MAX_SESSION=5      
  #   ports:
  #    - "5900:25900"
  #    - "4444:24444"
  #   volumes:
  #     - /etc/timezone:/etc/timezone
  #     - /etc/localtime:/etc/localtime
  #     - /dev/shm:/dev/shm
  #     - /data/e2e-reports/files:/opt/files

  mongodb:
    restart: always
    image: mongo:3.0
    command: mongod --smallfiles --quiet --logpath=/dev/null
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/db:/data/db
      - /data/configdb:/data/configdb
